from typing import Tuple, Optional, Dict, Any
import pandas as pd
from backend.ml.insights_engine import load_best_dataset

def run_nlq(dataset_id: str, question: str) -> Tuple[str, Optional[str], Optional[Dict[str, Any]]]:
    """
    Runs a natural language query against the best available version of a dataset.
    """
    df = load_best_dataset(dataset_id)

    # Simple rule-based NLQ
    code = ""
    question = question.lower().strip()

    import re

    # "show the first/last N rows"
    match = re.match(r"show the (first|last) (\d+) rows", question)
    if match:
        direction = match.group(1)
        n = int(match.group(2))
        if direction == "first":
            code = f"result = df.head({n})"
        else:
            code = f"result = df.tail({n})"
    # "what are the columns"
    elif question == "what are the columns":
        code = "result = df.columns"
    # "describe the data"
    elif question == "describe the data":
        code = "result = df.describe()"
    else:
        return (
            "# Unable to answer this question. In a real app, this would be generated by an LLM.",
            "This question is too complex for the current NLQ engine.",
            None,
        )


    # Execute the generated code to get a preview
    # In a real app, this would be done in a secure sandbox
    try:
        # Create a local scope for exec to run in
        local_scope = {'df': df}
        exec(code, {}, local_scope)
        preview = local_scope['result']

        if isinstance(preview, pd.DataFrame):
            result_summary = f"Successfully executed query. Showing {len(preview)} rows."
            preview_records = preview.to_dict(orient="records")
        elif isinstance(preview, pd.Index):
            result_summary = "Successfully retrieved column list."
            preview_records = [{"columns": list(preview)}]
        else:
            result_summary = f"Query executed. Result is of type {type(preview).__name__}."
            preview_records = [{"result": str(preview)}]

    except Exception as e:
        result_summary = f"Error executing generated code: {e}"
        preview_records = None

    return code, result_summary, preview_records


