"""
GraphState: The shared state definition for the SAGA LangGraph Agent Swarm.

Every node in the graph receives this state as input and returns an updated copy.
Fields are carefully designed to cover all 4 agents: Router, SQL, Analyst, Cleaner.
"""

from typing import TypedDict, Optional, List, Dict, Any, Annotated
from langchain_core.messages import BaseMessage, HumanMessage
from langgraph.graph.message import add_messages


class GraphState(TypedDict):
    """
    The single source of truth flowing through every LangGraph node.
    """

    # --- Input (set once at entry by create_initial_state) ---
    messages: Annotated[List[BaseMessage], add_messages]  # Chat history (appends via add_messages)
    dataset_id: str               # UUID of the uploaded file
    table_name: str               # SQLite table name (e.g., "dataset_abc_123")
    schema_context: str           # LLM-ready schema string from FileIngestionManager

    # --- Routing (set by Router node, Step 4) ---
    route: str                    # "sql_agent" | "analyst_agent" | "cleaner_agent"

    # --- SQL Agent outputs (Step 5) ---
    generated_sql: Optional[str]              # The SQL query generated by Gemini
    sql_result_columns: Optional[List[str]]   # Column names from query result
    sql_result_rows: Optional[List[List[Any]]]  # Row data from query result
    sql_error: Optional[str]                  # Error message if SQL execution failed
    sql_retry_count: int                      # Self-correction attempts (max 3)

    # --- Analyst Agent outputs (Step 6) ---
    generated_code: Optional[str]             # Python/Plotly code generated by Gemini
    chart_json: Optional[Dict[str, Any]]      # Plotly fig.to_json() output
    narrative: Optional[str]                  # Text explanation of the analysis

    # --- Cleaner Agent outputs ---
    cleaning_log: Optional[Dict[str, Any]]    # What was cleaned and how
    cleaned_table_name: Optional[str]         # New SQLite table for cleaned data

    # --- Shared ---
    current_agent: str            # Tracks active agent (for UI streaming)
    error: Optional[str]          # Global error message


def create_initial_state(
    dataset_id: str,
    table_name: str,
    schema_context: str,
    user_message: str,
) -> dict:
    """
    Creates the initial state dict for a new LangGraph invocation.
    Called by the WebSocket handler (Step 8) when a user sends a query.

    Args:
        dataset_id: UUID of the uploaded dataset.
        table_name: The SQLite table name for this dataset.
        schema_context: The LLM-ready schema string.
        user_message: The user's natural language question.

    Returns:
        A dict matching the GraphState shape, ready for graph.invoke().
    """
    return {
        "messages": [HumanMessage(content=user_message)],
        "dataset_id": dataset_id,
        "table_name": table_name,
        "schema_context": schema_context,
        "route": "",
        "generated_sql": None,
        "sql_result_columns": None,
        "sql_result_rows": None,
        "sql_error": None,
        "sql_retry_count": 0,
        "generated_code": None,
        "chart_json": None,
        "narrative": None,
        "cleaning_log": None,
        "cleaned_table_name": None,
        "current_agent": "router",
        "error": None,
    }
